apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: unvt-grafana
data:
  grafana.ini: |
    [server]
    root_url = http://localhost:3000
    [security]
    admin_user = ${GF_SECURITY_ADMIN_USER}
    admin_password = ${GF_SECURITY_ADMIN_PASSWORD}