apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: unvt-grafana
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.unvt-prometheus.svc.cluster.local:80
        isDefault: true
