apiVersion: v1                              # Verwendete API-Version für Secrets
kind: Secret                                # Der Typ des Kubernetes-Objekts: ein Secret (Geheimnis)
metadata:
  name: grafana-secret                      # Der interne Name des Secrets, über den es referenziert wird
  namespace: unvt-grafana                   # Das Secret gehört zum Namespace "unvt-grafana"
type: Opaque                                # Standardtyp für benutzerdefinierte Schlüssel/Werte (also nicht TLS, Docker-Registry etc.)
stringData:                                 # Hier können Klartextwerte angegeben werden (werden intern automatisch Base64-kodiert)
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin123
