apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jira-ingress
  namespace: unvt-jira
spec:
  ingressClassName: nginx
  rules:
    - host: jira.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: jira-service
                port:
                  number: 80
