apiVersion: v1                              # Verwendete API-Version für Secrets
kind: Secret                                # Der Typ des Kubernetes-Objekts: ein Secret (Geheimnis)
metadata:
  name: jira-secret                         # Der interne Name des Secrets, über den es referenziert wird
  namespace: unvt-jira                      # Das Secret gehört zum Namespace "unvt-jira"
type: Opaque                                # Standardtyp für benutzerdefinierte Schlüssel/Werte (also nicht TLS, Docker-Registry etc.)
stringData:                                 # Hier können Klartextwerte angegeben werden (werden intern automatisch Base64-kodiert)
  POSTGRES_PASSWORD: geheim
  JIRA_DB_PASSWORD: geheim
