apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: unvt-wordpress
data:
  WORDPRESS_BLOG_NAME: "Schulprojekt"
  WORDPRESS_EMAIL: "admin@example.com"
  WORDPRESS_USERNAME: "admin"
  WORDPRESS_DATABASE_NAME: "bitnami_wordpress"
  WORDPRESS_DATABASE_USER: "root"
  WORDPRESS_DATABASE_HOST: "mariadb-service"
