apiVersion: v1
kind: Secret                                 # K8s-Ressource zum Speichern von sensitiven Daten
metadata:
  name: wordpress-secret
  namespace: unvt-wordpress
type: Opaque                                 # Typ Opaque = freier Text (Base64-codiert intern)
stringData:                                  # Schl端ssel-Werte direkt im Klartext (wird automatisch codiert)
  WORDPRESS_PASSWORD: "adminpasswort123"     # Passwort f端r WP-Admin
  MARIADB_ROOT_PASSWORD: "supergeheim"       # Passwort f端r Datenbank-Root-User
  WORDPRESS_DB_PASSWORD: "supergeheim"       # Passwort f端r Datenbank-Root-User
