apiVersion: v1                              # Verwendete API-Version für Secrets
kind: Secret                                # Der Typ des Kubernetes-Objekts: ein Secret (Geheimnis)
metadata:
  name: wordpress-secret                    # Der interne Name des Secrets, über den es referenziert wird
  namespace: unvt-wordpress                 # Das Secret gehört zum Namespace "unvt-wordpress"
type: Opaque                                # Standardtyp für benutzerdefinierte Schlüssel/Werte (also nicht TLS, Docker-Registry etc.)
stringData:                                 # Hier können Klartextwerte angegeben werden (werden intern automatisch Base64-kodiert)                       
  WORDPRESS_PASSWORD: "adminpasswort123"     
  MARIADB_ROOT_PASSWORD: "supergeheim"       
  WORDPRESS_DB_PASSWORD: "supergeheim"       
