apiVersion: v1                              # API-Version für Konfigurationsdaten; ConfigMaps sind in v1 enthalten
kind: ConfigMap                             # Der Typ dieses Kubernetes-Objekts: eine ConfigMap (Konfigurationsdaten)
metadata:
  name: prometheus-config                   # Interner Name der ConfigMap, über den sie im Deployment referenziert wird
  namespace: unvt-prometheus                # Namespace, in dem die ConfigMap gespeichert ist (muss zu den anderen Ressourcen passen)
data:                                       # Hier beginnt der Datenblock mit Schlüssel-Wert-Paaren
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'grafana'
        static_configs:
          - targets:
              - grafana-service.unvt-grafana.svc.cluster.local:80
      - job_name: 'wordpress-http'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://wordpress-service.unvt-wordpress.svc.cluster.local
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter.unvt-prometheus.svc.cluster.local:9115
