apiVersion: v1                              # API-Version für Konfigurationsdaten; ConfigMaps sind in v1 enthalten
kind: ConfigMap                             # Der Typ dieses Kubernetes-Objekts: eine ConfigMap (Konfigurationsdaten)
metadata:
  name: prometheus-config                   # Interner Name der ConfigMap, über den sie im Deployment referenziert wird
  namespace: unvt-prometheus                # Namespace, in dem die ConfigMap gespeichert ist (muss zu den anderen Ressourcen passen)
data:                                       # Hier beginnt der Datenblock mit Schlüssel-Wert-Paaren
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'wordpress'
        static_configs:
          - targets: ['wordpress-service.unvt-wordpress.svc.cluster.local:80']

      - job_name: 'jira'
        static_configs:
          - targets: ['jira-service.unvt-jira.svc.cluster.local:80']

      - job_name: 'mediawiki'
        static_configs:
          - targets: ['mediawiki-service.unvt-mediawiki.svc.cluster.local:80']
