apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: unvt-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'wordpress'
        static_configs:
          - targets: ['wordpress-service.unvt-wordpress.svc.cluster.local:80']

      - job_name: 'jira'
        static_configs:
          - targets: ['jira-service.unvt-jira.svc.cluster.local:80']

      - job_name: 'mediawiki'
        static_configs:
          - targets: ['mediawiki-service.unvt-mediawiki.svc.cluster.local:80']
