apiVersion: v1                              # Verwendete API-Version für Secrets
kind: Secret                                # Der Typ des Kubernetes-Objekts: ein Secret (Geheimnis)
metadata:
  name: prometheus-secret                   # Der interne Name des Secrets, über den es referenziert wird
  namespace: unvt-prometheus                # Das Secret gehört zum Namespace "unvt-prometheus"
type: Opaque                                # Standardtyp für benutzerdefinierte Schlüssel/Werte (also nicht TLS, Docker-Registry etc.)
stringData:                                 # Hier können Klartextwerte angegeben werden (werden intern automatisch Base64-kodiert)
  PROM_USER: admin
  PROM_PASS: admin123
