apiVersion: v1                              # Verwendete API-Version für Secrets
kind: Secret                                # Der Typ des Kubernetes-Objekts: ein Secret (Geheimnis)
metadata:
  name: mediawiki-secret                    # Der interne Name des Secrets, über den es referenziert wird
  namespace: unvt-mediawiki                 # Das Secret gehört zum Namespace "unvt-mediawiki"
type: Opaque                                # Standardtyp für benutzerdefinierte Schlüssel/Werte (also nicht TLS, Docker-Registry etc.)
stringData:                                 # Hier können Klartextwerte angegeben werden (werden intern automatisch Base64-kodiert)
  MARIADB_ROOT_PASSWORD: "supergeheim"       
  MEDIAWIKI_DB_PASSWORD: mwpass123          