apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
  namespace: unvt-mediawiki
spec:
  type: ClusterIP
  selector:
    app: mediawiki
  ports:
  - port: 80                                 # Service-Port im Cluster
    targetPort: 8080                         # Weiterleitung an Container-Port